### ISSUE TITLE
Script should reset terminal color to default after exit

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/MARS#46]
Expected behavior: after the MARS automation script is done, the terminal text color should be reset to default.

Current behavior: the terminal text color is still blue after MARS exits.

**Comment by ritik-malik** [comment]
Thanks @GeorgLink,
We've updated the scripts. Please let us know if the issue still persists

**Comment by GeorgLink** [comment]
Yes, it works. Thank you very much!
